---
title: "BullpenApp Project Script"
author: "Carter Hall"
---

Email: *halljc76@live.unc.edu*

To-Do:
- Make Tilt UI 
- Horiz., Vert. Break vs. Time, vs. Each Other  Graphs
- Release point CLUSTER, averages, and outliers (HT)
- Add Balls, Strikes to Summ. Stats?


```{r Libraries, message = FALSE, warning = FALSE}
options(shiny.maxRequestSize = 50*1024^2)
library(shiny)
library(shinydashboard)
library(DT)
library(ggplot2)
library(dplyr)
library(shinythemes)
library(plotly)
library(DBI)
library(dbplyr)
library(RSQLite)
library(rrcov)
```

```{r Functions message = FALSE, warning = FALSE}
addTableDB <- function(conn, filename, tablename) {
  tables <- c(unname(as.list(queryDB(conn, "SELECT name FROM sqlite_master"))))
  if (!(tablename %in% tables[[1]])) {
    fn <- read.csv(filename)
    dbWriteTable(conn, tablename, fn)
  }
}

queryDB <- function(conn, query) {
  return(dbGetQuery(conn, query))
}

addData <- function(conn, filename, tablename) {
  
  # QUERY: Get all names of tables in database.
  tables <- c(unname(as.list(queryDB(conn, "SELECT name FROM sqlite_master"))))
  
  if (!(tablename %in% tables[[1]])) {
    fn <- read.csv(filename)
    dbWriteTable(conn, tablename, fn)
    
    suppressWarnings( 
      expr = {
        cols <- names(queryDB(conn, gsub(pattern = "_", replacement = tablename, x = "SELECT * FROM _")))
        for (col in cols) {
          # Query: Set any blank field from TM to be a null value.
          q <- gsub(pattern = "_", replacement = col, 
                    x = gsub(pattern = "-",
                             replacement = tablename, 
                             x = "UPDATE - SET _ = NULL WHERE _ = '' "))
          queryDB(conn, q)
        }
      }
    )
    
    queryDB(conn, gsub(
      pattern = "-",
      replacement = tablename,
      # QUERY: Redefine 'Undefined' pitches to 'Warmup'
      x = "UPDATE - SET TaggedPitchType = 'Warmup' 
                  WHERE TaggedPitchType = 'Undefined' "
    )
    )
    
  }
}

obtainSession <- function(player) {
  # QUERY: Return a list of days when this player logged sessions.
  q <- "SELECT DISTINCT Date FROM TestData WHERE Pitcher = '_'"
  result <- list(unname(queryDB(conn, gsub(pattern = '_', replacement = player, x = q)))[[1]])
  names(result) <- result
  return(result)
}

getDate <- function() {
  date <- Sys.Date()
  return(
    gsub(pattern = " ",
         replacement = "",
         x= paste(substr(date, 6, 7), "/", 
                  substr(date, 9, 10), "/", 
                  substr(date, 1, 4)))
  )
}

averageTilt <- function(pitcher, sessionDate) {
  df <- queryDB(conn, 
                paste("SELECT TaggedPitchType, Tilt FROM TestData 
                    WHERE Pitcher = '", pitcher,
                    "'AND Date = '", sessionDate, "'
                    ORDER BY TaggedPitchType", sep = "")
  ) 
  
  df <- na.omit(df)
  ret <- data.frame()
  
  for (pt in unique(df$TaggedPitchType)) {
    if (pt != "Warmup") {
      df2 <- subset(df, df$TaggedPitchType == pt)
      m <- c()
      for (i in 1:nrow(df2)) {
        tilt <- df2$Tilt[i]
        hr <- strtoi(substr(tilt, 1, gregexpr(":", tilt)[[1]][1] - 1))
        min <- strtoi(substr(tilt, gregexpr(":", tilt)[[1]][1] + 1, nchar(tilt)))
        
        m[i] <- (hr * 60) + min
      }
      
      
      nearhr <- round(mean(m) / 60)
      nearmin <- round(round(mean(m) - round(mean(m) / 60) * 60) / 15) * 15 

      if (nearmin < 0) {
        nearhr <- nearhr - 1
      }
      
      nearhr <- toString(nearhr)
      if (nearmin == 0) {
        nearmin <- '00'
      } else {
        if (nearmin >= 52.5 || nearmin <= 7.5) {
          nearmin <- '00'
        } else if (nearmin > 7.5 && nearmin < 22.5) {
          nearmin <- '15'
        } else if (nearmin > 22.5 && nearmin < 37.5) {
          nearmin <- '30'
        } else {
          nearmin <- '45'
        }
      }
      
      ret <- rbind(ret, c(pt, paste(nearhr, ":", nearmin, sep = "")))
    }
  }
  
  colnames(ret) <- c("Pitch", "Avg. Tilt")
  return(ret)
}

summaryStats <- function(pitcher, sessionDate) {
  
  ret <- queryDB(conn, 
                 paste("SELECT TaggedPitchType AS Pitch, 
                 COUNT(TaggedPitchType) AS `Num. Thrown`, 
                 ROUND(AVG(ZoneSpeed), 1) AS `Avg. Velo`, 
                 ROUND(AVG(SpinRate), 0) 
                 AS `Avg. Spin`
                 FROM TestData 
                 WHERE Pitcher = '", pitcher, "' 
                 AND Date = '", sessionDate, "'
                 GROUP BY TaggedPitchType", sep = "")
          )
  ret <- subset(ret, ret$Pitch != 'Warmup')
  ret2 <- averageTilt(pitcher, sessionDate)
  ret <- merge(ret, ret2, by = "Pitch") 
  ret <- ret[order(ret[,2], decreasing = TRUE),] 
  row.names(ret) <- c()
  return(ret)
}

locationDist <- function(pitcher, plotBool, sessionDate) {
  
  # QUERY: All queries in this function select (y,z) and pitch type.
  
  df <- queryDB(conn, 
                paste("SELECT PlateLocSide, PlateLocHeight, 
                TaggedPitchType,
                Tilt, ZoneSpeed FROM TestData
                WHERE Pitcher = '", pitcher, "' 
                AND Date = '", sessionDate, "'", sep = ""))
  df <- na.omit(df)
  df <- subset(df, df$TaggedPitchType != 'Warmup')
  
  if (plotBool){
    fig <- suppressMessages(
      plot_ly(
        type = "scatter",
        mode = "markers",
        x = df$PlateLocSide,
        y = df$PlateLocHeight,
        color = ~as.factor(df$TaggedPitchType),
        hoverinfo = "text",
        text = ~paste(df$TaggedPitchType, "\nTilt: ", df$Tilt, 
                      "\nVelo: ", round(df$ZoneSpeed, 1), " MPH", sep = "")
      ) %>% layout(
        shapes = list(type = "rect",
                      line = list(color = "blue"),
                      x0 = -0.783333, 
                      x1 = 0.783333,
                      xref = "x",
                      y0 = 1.525,
                      y1 = 3.316,
                      yref = "y"),
        xaxis = list(range = c(-2, 2)),
        yaxis = list(range = c(-0.5, 4))
      ) 
    )
    
    return(fig)
  }
  
  return(df)
}

horzVert <- function(pitcher, sessionDate) {
  df <- queryDB(conn, paste("SELECT TaggedPitchType, HorzBreak, VertBreak 
                         FROM TestData 
                         WHERE Pitcher = '", pitcher, "' 
                           AND Date = '", sessionDate, "'", sep = ""))
  df <- na.omit(df)
  df <- subset(df, df$TaggedPitchType != "Warmup")
  
  plot_ly(
    data = df, 
    type = "scatter",
    mode = "markers",
    x = ~df$HorzBreak,
    y = ~df$VertBreak,
    color = ~df$TaggedPitchType
  ) %>% 
    layout(xaxis = list(title = "Horizontal Break (in.)"),
           yaxis = list(title = "Vertical Break (in.)"))
}

timeGraphs <- function(pitcher, sessionDate, flag) {
  
  df <- queryDB(conn, 
                paste("SELECT ROW_NUMBER() OVER(PARTITION BY TaggedPitchType) AS 
               Row, TaggedPitchType, ZoneSpeed, SpinRate, HorzBreak, VertBreak
           FROM TestData WHERE Pitcher =  '", pitcher, "' 
           AND Date = '", sessionDate, "'
           AND ZoneSpeed IS NOT NULL 
           AND SpinRate IS NOT NULL", sep = ""))
  df <- na.omit(df)
  df <- subset(df, df$TaggedPitchType != 'Warmup')
  
  if (flag == 1) {
    return(
      plot_ly(data = df %>% group_by(df$TaggedPitchType),
              x = ~df$Row, 
              y = ~df$ZoneSpeed, 
              type = "scatter",
              color = ~df$TaggedPitchType,
              mode = "lines+markers",
              hoverinfo = "text",
              text = ~paste(df$Row, ": ", round(df$ZoneSpeed, 1), " MPH", 
                            sep = "")) %>% 
        layout(xaxis = list(            
          tickvals = ~df$Row,
          tickangle = 0,
          title = "Pitch #"),
          
          yaxis = (
            list(title = "Velo (MPH)")
          )
        )
    )
  } else if (flag == 2) {
    return(
      plot_ly(data = df %>% group_by(df$TaggedPitchType),
              x = ~df$Row, 
              y = ~df$SpinRate, 
              type = "scatter",
              color = ~df$TaggedPitchType,
              mode = "lines+markers",
              hoverinfo = "text",
              text = ~paste(df$Row, ": ", round(df$SpinRate, 0), " RPM", 
                            sep = "")) %>% 
        layout(xaxis = list(            
          tickvals = ~df$Row,
          tickangle = 0,
          title = "Pitch #"),
          
          yaxis = list(
            title = "Spin (RPM)"
          )
        )
    )
  } else if (flag == 3) {
    return(
      plot_ly(data = df %>% group_by(df$TaggedPitchType),
              x = ~df$Row, 
              y = ~df$VertBreak, 
              type = "scatter",
              color = ~df$TaggedPitchType,
              mode = "lines+markers",
              hoverinfo = "text",
              text = ~paste(df$Row, ": ", round(df$VertBreak, 0), " in.", 
                            sep = "")) %>% 
        layout(xaxis = list(            
          tickvals = ~df$Row,
          tickangle = 0,
          title = "Pitch #"),
          
          yaxis = list(
            title = "Vertical Break (inches)"
          )
        )
    )
  } else {
    return(
      plot_ly(data = df %>% group_by(df$TaggedPitchType),
              x = ~df$Row, 
              y = ~df$HorzBreak, 
              type = "scatter",
              color = ~df$TaggedPitchType,
              mode = "lines+markers",
              hoverinfo = "text",
              text = ~paste(df$Row, ": ", round(df$HorzBreak, 0), " in.", 
                            sep = "")) %>% 
        layout(xaxis = list(            
          tickvals = ~df$Row,
          tickangle = 0,
          title = "Pitch #"),
          
          yaxis = list(
            title = "Horizontal Break (inches)"
          )
        )
    )
  }
}

# Deprecated version of releasePoints
releasePointsOLD <- function(pitcher, sessionDate) {
  df <- queryDB(conn, 
                paste("SELECT RelSide, RelHeight, 
                        PlateLocSide, PlateLocHeight,
                        ZoneSpeed, SpinRate, TaggedPitchType 
                  FROM TestData 
                  WHERE Pitcher = '", pitcher, "'",
                  "\n AND Date = '", sessionDate, "'", sep = ""))
  
  df <- na.omit(df)
  df <- subset(df, df$TaggedPitchType != "Warmup")
  df$sz <- ifelse(abs(df$PlateLocSide) <= 0.78333, 
                  ifelse(df$PlateLocHeight >= 1.515, 
                         ifelse(df$PlateLocHeight <= 3.316, T, F), F), F)
  
  plot_ly(data = df, 
          x = ~df$RelSide,
          y = ~df$RelHeight, 
          type = "scatter", 
          mode = "markers", 
          color = ~df$TaggedPitchType,
          hoverinfo = "text",
          text = ~paste(round(ZoneSpeed, 1), " MPH\n", 
                        round(SpinRate, 0), " RPM\n",
                        ifelse(sz, "Strike", "Ball"))
  ) %>% 
    layout(xaxis = list(title = "Distance from Center of Rubber (ft)"),
           yaxis = list(title = "Height above Home Plate (ft)")) 
}

releasePoints <- function(pitcher, sessionDate) {

  # Retrieve necessary data
  df <- queryDB(conn, paste("SELECT TaggedPitchType, RelSide, RelHeight
                       FROM TestData 
                       WHERE Pitcher = '", pitcher, "' 
                         AND Date = '", sessionDate, "'", sep = ""))
  
  df <- na.omit(df)
  df <- subset(df, TaggedPitchType != "Warmup")
  
  plot <- plot_ly(
    data = df,
    type = "scatter",
    mode = "markers"
  )
  colors <- c("red", "blue", "green", "orange", "purple") 
  i = 1
  # For each pitch type, identify outliers
  for (pt in unique(df$TaggedPitchType)) {
    temp <- subset(df, df$TaggedPitchType == pt)
    avg <- data.frame(x = mean(temp$RelSide),
                  y = mean(temp$RelHeight))
    
    c <- colors[i]
    mcd <- tryCatch(
      expr = {
        covMcd(x = temp[,2:3])
      },
      error = function(cond) {
        return(NULL)
      }
    )
    
    
    # Found this from a paper on multivariate outliers
    # and a cross-validated post. Figured implementing it 
    # would be better than depending on the built-in
    mahalanobisDist <- function(x, mu, cov) {
      return(sqrt(t((x - mu)) %*% solve(cov) 
                  %*% (x - mu)))
    }
    
    
    if (!is.null(mcd)) {
      distances <- apply(
        temp[,2:3], 
        1, 
        function(x) {
          mahalanobisDist(x, mcd$center, mcd$cov)
        }
      )
      
      cutoff <- sqrt(qchisq(p = 0.975, df = 2))
      
      outliers <- df[which(distances >= cutoff),]
      
      ellipse_mcd <- data.frame(car::ellipse(center = mcd$center,
                                             shape = mcd$cov,
                                             radius= r, 
                                             segments=100,draw=FALSE))
      
      plot <- plot %>% 
        add_polygons(
          data = ellipse_mcd,
          x = ~x,
          y = ~y,
          name = pt,
          color = c
        )
      plot <- plot %>% add_trace(
        data = outliers,
        type = "scatter",
        mode = "markers",
        x = ~RelSide,
        y = ~RelHeight,
        name = pt, 
        color = c
      )
    } else {
      plot <- plot %>% add_trace(
          data = temp,
          type = "scatter",
          mode = "markers",
          x = ~RelSide,
          y = ~RelHeight,
          name = pt,
          color = c
          )
    }
    plot <- plot %>% add_trace(
        type = "scatter",
        mode = "markers",
        data = avg,
        x = ~x,
        y = ~y,
        name = pt,
        color = c,
        marker = list(symbol = "diamond"),
        showlegend = FALSE
      )
    i = i + 1
  }
  
  plot <- plot %>% 
  layout(xaxis = list(title = "Dist. from Rubber Center (ft)",
                      range = c(-5, 5)), 
                  yaxis = list(title = "Dist. above Home Plate (ft)",
                               range = c(0, 6)))
  
  return(plot)
}
```

```{r UI}
ui <- navbarPage(
  "The Tar Pen",
  tabPanel("Individual Session",
           fluid = TRUE,
           icon = icon("calendar-day")),
  
  sidebarLayout(
    
    sidebarPanel(
      width = 3,
      fluidRow(
        column(9,
               h3("Player Name"),
               selectInput(inputId = "playerSelect",
                           label = NULL,
                           choices = NULL),
               
               h3("Session Date"),
               selectInput(inputId = "sessionSelect",
                           label = NULL,
                           choices = NULL)
        )
      )
    ),
    
    mainPanel(
      
      tabsetPanel(
        type = "tabs",
        tabPanel(
          "Horiz. vs. Vert. Break", 
          id = "hvBreak", 
          br(),
          br(),
          plotlyOutput(outputId = "breakDisplay"),
        ),
        
        
        tabPanel(
          "Metrics over Time", 
          id = "timeGraphs",
          br(),
          h3("Velocity"),
          plotlyOutput(
            outputId = "veloDisplay", height = "200px"),
          h3("Spin Rate"),
          plotlyOutput(
            outputId = "spinDisplay", height = "200px"),
          h3("Vertical Break"),
          plotlyOutput(
            outputId = "vertDisplay", height = "200px"),
          h3("Horizontal Break"),
          plotlyOutput(
            outputId = "horzDisplay", height = "200px")
        ),
        
        tabPanel(
          "Release Points",
          id = "rlsGraph",
          br(),
          h5("How To Read"),
          h6("Any 'points' with no ellipse of the same color is data for which there were too few points to draw an ellipse. Points outside of their same-colored ellipse are 'outliers' -- possibly atypical releases of that pitch. 'Diamonds' are averages."),
          h6("If anything is small, press the 'Autoscale' button! Hover over the plot, and press the button to the left of 
             'Home'."),
          br(),
          plotlyOutput(outputId = "relDisplay")
        ),
        
        tabPanel("Summary Stats",
                 id = "summTable",
                 br(),
                 br(),
                 dataTableOutput(outputId = "summStatsDisplay")
        ),
        tabPanel("Notes", 
                 id = "notesTable",
                 br(),
                 br(),
                 div(style = "display:inline-block",
                     textInput(inputId = "notesInput", 
                               label = "Enter Note Here")),
                 div(style = "display:inline-block",
                     actionButton(inputId = "notesSubmit", 
                                  label = "Add Note",
                                  class = "btn-success")),
                 dataTableOutput(outputId = "notesDisplay")
        )
      )
    )
  )
)
```

```{r Server}
server <- function(input, output, session) {
  
  # 'conn' is a GLOBAL var
  
  flags <- reactiveValues(ps = NULL, ss = NULL)
  
  updateSelectInput(
    
    session = session,
    inputId = "playerSelect",
    # QUERY: Return all names of pitchers in alphabetical order.
    choices = queryDB(conn, "SELECT DISTINCT Pitcher FROM TestData
                              ORDER BY Pitcher ASC"),
    selected = NULL
    
  )
  
  observeEvent(input$playerSelect,
               {
                 flags$ps <- input$playerSelect
                 
                 updateSelectInput(session = session,
                                   inputId = "sessionSelect",
                                   # QUERY: For a pitcher, obtain
                                   #        all dates of prev. sessions.
                                   choices = obtainSession(flags$ps)
                 )
               }
  )
  
  observeEvent(input$sessionSelect, 
               {
                 flags$ss <- input$sessionSelect
               }
  )
  
  output$breakDisplay <- renderPlotly(
    expr = {
      horzVert(flags$ps, flags$ss)
    }
  )
  
  output$veloDisplay <- renderPlotly(
    expr = {
      timeGraphs(flags$ps, flags$ss, 1)
    }
  )
  
  output$spinDisplay <- renderPlotly(
    expr = {
      timeGraphs(flags$ps, flags$ss, 2)
    }
  )
  
  output$vertDisplay <- renderPlotly(
    expr = {
      timeGraphs(flags$ps, flags$ss, 3)
    }
  )
  
  output$horzDisplay <- renderPlotly(
    expr = {
      timeGraphs(flags$ps, flags$ss, 4)
    }
  )
  
  output$relDisplay <- renderPlotly(
    expr = {
      releasePoints(flags$ps, flags$ss)
    }
  )
  
  output$notesDisplay <- renderDataTable(
    expr = {
      # QUERY: Select all notes and dates for this pitcher.
      queryDB(conn,
              paste("SELECT Date, Note FROM Notes 
                                    WHERE Pitcher = '", 
                    input$playerSelect, "'", 
                    "\n ORDER BY Date DESC", sep = "")
      )
    }
  )
  
  observeEvent(input$notesSubmit, 
               {
                 queryDB(conn, 
                         # QUERY: Insert a new note, marked today.
                         paste("INSERT INTO Notes VALUES ", "('", 
                               input$playerSelect, "'", ", '", 
                               getDate(), "'", ", '", 
                               input$notesInput, "'", ")", sep = ""
                         )
                 )
                 updateTextInput(session = session,
                                 inputId = "notesInput", 
                                 label = "Enter Note Here",
                                 value = " "
                 )
               })
  
  output$summStatsDisplay <- renderDataTable(
    expr = {
      # If the UI seems to throw an error... don't know why. It works nonetheless!
      
      # QUERY: Get the summary statistics (pitch, percent thrown, velo, spin).
      summaryStats(flags$ps, flags$ss)
    }
  )
  
  session$onSessionEnded(function() {
    dbDisconnect(conn)
  })
}
```

```{r Main}
### MAIN CHUNK ###

# Run This Code Before shinyApp()
# Use a .sqlite extension, not a .db
# If an error of 'invalid connection' occurs somewhere, refresh this line.
# Also, the second parameter doesn't have to exist already
conn <- dbConnect(RSQLite::SQLite(), "bullpen.sqlite")

# Make SURE the final param in this call matches the 
# corresponding name given to the server-side queries!!!!
addData(conn, "TestData.csv", "TestData")

# DO NOT CHANGE THIS LINE :)
invisible(queryDB(conn, "CREATE Table IF NOT EXISTS Notes (Pitcher text, Date text, Note text)"))

## IMPORTANT ##
# Sometimes, the app throws error messages on-startup. 
# This is, to the best of my knowledge, simply because some things take awhile
# to execute. (This hasn't happened under the Tabset UI... *knocks on wood*.)

# The code SHOULD function (startup time probably around 5 seconds... but
# I doubt this would be too much of an issue as it isn't the homepage of the app,
# and anything could run before someone gets to it.)

# Do, however, let anyone using this know that if it complains, it's not them!
###############
shinyApp(ui, server) 
```


